name: machine_learning
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - streamlit
  - pandas
  - pyarrow
  - geopandas
  - shapely
  - pyproj
  - fiona
  - gdal
  - matplotlib
  - scikit-learn
  - requests
  - altair
  - ipykernel
  - ipywidgets
  - jinja2
  - joblib
  - numpy
  - statsmodels
  - pip:
      - pydeck
      - watchdog

